### ISSUE TITLE
strip bbcode?

### ISSUE THREAD

**Issue by ralyodio** [svenslaggare/BBCodeParser#1]
Is there anyway to simply strip all bbcode tags from a string?

**Comment by svenslaggare** [comment]
No. But it is not that hard to implement.

**Comment by svenslaggare** [comment]
I have made the necessary changes. Invoke "parseString" with true after the string to parse. For example: parseString("[b]test[/b]", true) returns "test".

**Comment by ralyodio** [comment]
Can you test if it works with this? `[COLOR steelblue][I][B] Foobar[/B][/I][/COLOR]`
